service: MeesmanAPIWrapper

package:
  individually: true

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: meesman-api-wrapper
      description: Meesman API Wrapper
      compatibleRuntimes:
        - python3.8

functions:
  app:
    timeout: 30
    package:
      include:
        - "main.py"
        - "meesmanwrapper.py"
        - "constants.py"
        - "authentication.py"
        - "authentication.key"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /healthcheck
      - http:
          method: any
          path: /combined
      - http:
          method: any
          path: /getauthtoken
      - http:
          method: any
          path: /getmeesmandata
          request:
            parameters:
              querystrings:
                token: true
      - http:
          method: any
          path: /sendpushmessage
          request:
            parameters:
              querystrings:
                token: true
                title: true
                body: true
      - http:
          method: any
          path: /sendpushmessagetoall
          request:
            parameters:
              querystrings:
                title: true
                body: true
      - http:
          method: any
          path: /registerpushtoken
          request:
            parameters:
              querystrings:
                token: true
