service: MeesmanAPIWrapper

package:
  individually: true

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, "prod"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: meesman-api-wrapper
      description: Meesman API Wrapper
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      include:
        - "main.py"
        - "meesmanwrapper.py"
        - "constants.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /healthcheck
      - http:
          method: any
          path: /
          throttling:  # Throttling configuration for this endpoint
            burstLimit: 5  # Maximum number of requests that are allowed in a burst
            rateLimit: 5  # The rate at which requests are allowed per second
          request:
            headers:
              password: true
              username: true
